Integrate Google Translate API to translate sentence and add CSS
emilyzhaoo/step pull request #17
Opened 2020-06-11 16:40 UTC by emilyzhaoo

2020-06-11 20:46 UTC, azhang72 requested changes

2020-06-11 20:46 UTC, StarIU072 commented on portfolio/src/main/webapp/script.js
> +
nit: remove extra empty line

2020-06-11 20:46 UTC, StarIU072 commented on portfolio/src/main/webapp/script.js
>  }
nit: newline at end of file.

2020-06-11 20:46 UTC, StarIU072 commented on portfolio/src/main/webapp/script.js
> +    const loadingContainer = document.getElementById('result');
Why does the |loadingContainer| have id "result"?

2020-06-12 16:06 UTC, EkkiD requested changes

2020-06-12 16:06 UTC, EkkiD commented on portfolio/src/main/java/com/google/sps/servlets/TranslateServlet.java
> +// Copyright 2019 Google LLC
nit:2020

2020-06-12 16:06 UTC, EkkiD commented on portfolio/src/main/java/com/google/sps/servlets/TranslateServlet.java
> +    String languageCode = request.getParameter("languageCode");
consider renaming this a parameter to make it clear whether this is the source language or the destination language

2020-06-12 16:06 UTC, EkkiD commented on portfolio/src/main/webapp/index.html
> +    <script src="script.js"></script>
nit: remove trailing spaces

2020-06-12 16:06 UTC, EkkiD commented on portfolio/src/main/webapp/script.js
> +
nit: remove trailing spaces

2020-06-12 16:06 UTC, EkkiD commented on portfolio/src/main/java/com/google/sps/servlets/TranslateServlet.java
> +    String languageCode = request.getParameter("languageCode");
or "original" and "target"... whatever terminology is best suited in your mind

2020-06-12 17:52 UTC, EkkiD requested changes

2020-06-12 17:52 UTC, EkkiD commented on portfolio/src/main/java/com/google/sps/servlets/TranslateServlet.java
> +    String targetLanguage = request.getParameter("languageCode");
I think it's worth renaming the parameter here too. It makes the API easier to use for people who might be less familiar with it.

2020-06-15 13:43 UTC, azhang72 approved these changes
lgtm with a nit

2020-06-15 13:43 UTC, StarIU072 commented on portfolio/src/main/webapp/index.html
> +</html>
nit: newline at end of file

2020-06-15 13:45 UTC, StarIU072 commented on portfolio/src/main/webapp/script.js
> +    const loadingContainer = document.getElementById('result');
Did you miss this?

2020-06-15 13:45 UTC, EkkiD approved these changes
LGTM

2020-06-15 13:58 UTC, merged